name: repo_viewer
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  dartz: ^0.10.0
  dio: ^4.0.0
  flash: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^0.14.2
  hooks_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/hooks_riverpod
  json_annotation: ^4.4.0
  material_design_icons_flutter: ^5.0.6595
  oauth2: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.8
  sembast: ^3.1.2
  webview_flutter: ^3.0.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^6.1.4

dependency_overrides:
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/flutter_riverpod
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      ref: 147be70df096015af0633456a951d8f2f9c66dc9
      path: packages/riverpod

flutter:
  uses-material-design: true
