@baseUrl = https://api.github.com

@token = {{githubToken}}

@acceptJson = application/vnd.github.v3+json

@acceptHTML = application/vnd.github.v3.html+json

GET {{baseUrl}}/user/starred
    ?sort=stars
    &order=desc
    &page=1
Authorization: token {{token}}
Accept: {{acceptJson}}
#If-None-Match: W/"fc39e9c03134895d01a6b94e1cb27b1d805e339a1a8d41230c8ab02c239f112e"

###

GET {{baseUrl}}/search/repositories
    ?q=tetris+language:assembly
    &sort=stars
    &order=desc
    &page=1
# Authorization: token {{token}}
Accept: {{acceptJson}}

###

GET {{baseUrl}}/repos/daniel-e/tetros/readme
Authorization: token {{token}}
Accept: {{acceptHTML}}

###

PUT {{baseUrl}}/user/starred/daniel-e/tetros
Authorization: token {{token}}
Accept: {{acceptJson}}
Content-Length: 0

###

DELETE {{baseUrl}}/user/starred/daniel-e/tetros
Authorization: token {{token}}
Accept: {{acceptJson}}

###

GET {{baseUrl}}/user/starred/daniel-e/tetros
Authorization: token {{token}}
Accept: {{acceptJson}}