@baseUrl = https://api.github.com

@token = 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

@acceptJson = application/vnd.github.v3+json

@acceptHTML = application/vnd.github.v3.html+json

GET {{baseUrl}}/user/starred
    ?sort=stars
    ?order=desc
    ?page=1
Authorization: token {{token}}
Accept: {{acceptJson}}

###

GET {{baseUrl}}/search/repositories
    ?q=tetris+language:assembly
    &sort=stars
    &order=desc
    &page=1
Authorization: token {{token}}
Accept: {{acceptJson}}

###

GET {{baseUrl}}/repos/daniel-e/tetros/readme
Authorization: token {{token}}
Accept: {{acceptHTML}}

###

PUT {{baseUrl}}/user/starred/daniel-e/tetros
Authorization: token {{token}}
Accept: {{acceptJson}}
Content-Length: 0

###

DELETE {{baseUrl}}/user/starred/daniel-e/tetros
Authorization: token {{token}}
Accept: {{acceptJson}}

###

GET {{baseUrl}}/user/starred/daniel-e/tetros
Authorization: token {{token}}
Accept: {{acceptJson}}